const teamLogos = {
  ATL: require('../assets/team_logo/ATL.png'),
  BKN: require('../assets/team_logo/BKN.png'),
  BOS: require('../assets/team_logo/BOS.png'),
  CHA: require('../assets/team_logo/CHA.png'),
  CHI: require('../assets/team_logo/CHI.png'),
  CLE: require('../assets/team_logo/CLE.png'),
  DAL: require('../assets/team_logo/DAL.png'),
  DEN: require('../assets/team_logo/DEN.png'),
  DET: require('../assets/team_logo/DET.png'),
  GSW: require('../assets/team_logo/GSW.png'),
  HOU: require('../assets/team_logo/HOU.png'),
  IND: require('../assets/team_logo/IND.png'),
  LAC: require('../assets/team_logo/LAC.png'),
  LAL: require('../assets/team_logo/LAL.png'),
  MEM: require('../assets/team_logo/MEM.png'),
  MIA: require('../assets/team_logo/MIA.png'),
  MIL: require('../assets/team_logo/MIL.png'),
  MIN: require('../assets/team_logo/MIN.png'),
  NOP: require('../assets/team_logo/NOP.png'),
  NYK: require('../assets/team_logo/NYK.png'),
  OKC: require('../assets/team_logo/OKC.png'),
  ORL: require('../assets/team_logo/ORL.png'),
  PHI: require('../assets/team_logo/PHI.png'),
  PHX: require('../assets/team_logo/PHX.png'),
  POR: require('../assets/team_logo/POR.png'),
  SAC: require('../assets/team_logo/SAC.png'),
  SAS: require('../assets/team_logo/SAS.png'),
  TOR: require('../assets/team_logo/TOR.png'),
  UTA: require('../assets/team_logo/UTA.png'),
  WAS: require('../assets/team_logo/WAS.png'),
};

export default teamLogos;
